bind-key -r Tab next-window
bind-key -r BTab previous-window

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r J join-pane -t :+
bind -r B break-pane
